# Generated by Django 5.0.4 on 2024-05-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0003_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='developer_project_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='development',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
