# Generated by Django 5.0.4 on 2024-05-11 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0004_product_developer_project_number_product_development'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='area',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
