# Generated by Django 5.0.4 on 2024-05-11 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0006_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 9, 54, 34, 682179, tzinfo=datetime.timezone.utc)),
        ),
    ]
