# Generated by Django 5.0.4 on 2024-05-11 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0008_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 9, 56, 50, 996561, tzinfo=datetime.timezone.utc)),
        ),
    ]
