# Generated by Django 5.0.4 on 2024-05-11 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0009_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 11, 10, 1, 6, 986571, tzinfo=datetime.timezone.utc)),
        ),
    ]
