# Generated by Django 5.0.4 on 2024-06-09 10:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0014_alter_about_about_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 9, 10, 34, 16, 620472)),
        ),
        migrations.AlterField(
            model_name='product',
            name='per_meter_price',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
