# Generated by Django 5.0.4 on 2024-07-25 07:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_link', models.CharField(max_length=128)),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Building Detials',
                'db_table': 'building_details',
            },
        ),
        migrations.CreateModel(
            name='BuildingHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_link', models.CharField(max_length=128)),
                ('highlight', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Building Highlights',
                'db_table': 'building_highlights',
            },
        ),
        migrations.CreateModel(
            name='BuildingImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_link', models.CharField(max_length=128)),
                ('img_link', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Building Images',
                'db_table': 'building_images',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Property Type',
                'db_table': 'property_type',
            },
        ),
        migrations.CreateModel(
            name='UnitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_link', models.CharField(max_length=128)),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Unit Details',
                'db_table': 'unit_detials',
            },
        ),
        migrations.CreateModel(
            name='UnitPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_link', models.CharField(max_length=128)),
                ('img_link', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Unit Photos',
                'db_table': 'unit_photos',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=128)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='area.city')),
            ],
            options={
                'verbose_name_plural': 'Areas',
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=128)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='area.area')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='area.city')),
            ],
            options={
                'verbose_name_plural': 'Communities',
                'db_table': 'communities',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=128)),
                ('building_link', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('location', models.CharField(blank=True, max_length=64, null=True)),
                ('about', models.TextField(blank=True, default=None, null=True)),
                ('publish_status', models.PositiveSmallIntegerField(choices=[(1, 'Publish'), (0, 'Draft'), (2, 'Must Be Check')], default=0)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='area.area')),
                ('details', models.ManyToManyField(blank=True, null=True, to='area.buildingdetail')),
                ('highlight', models.ManyToManyField(blank=True, null=True, to='area.buildinghighlight')),
                ('img_link', models.ManyToManyField(blank=True, null=True, to='area.buildingimg')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='area.city')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='area.community')),
            ],
            options={
                'verbose_name_plural': 'Buildings',
                'db_table': 'buildings',
            },
        ),
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('publish_status', models.PositiveSmallIntegerField(choices=[(1, 'Publish'), (0, 'Draft'), (2, 'Must Be Check')], default=0)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='area.area')),
                ('buildings', models.ManyToManyField(to='area.building')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='area.city')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='area.community')),
            ],
            options={
                'verbose_name_plural': 'Complexs',
                'db_table': 'complexs',
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('photo', models.CharField(max_length=128)),
                ('sale_properties', models.PositiveSmallIntegerField()),
                ('rent_properties', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('property_types', models.ManyToManyField(to='area.propertytype')),
                ('service_areas', models.ManyToManyField(to='area.area')),
                ('service_cities', models.ManyToManyField(to='area.city')),
            ],
            options={
                'verbose_name_plural': 'Real Estate',
                'db_table': 'real_estates',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('photo', models.CharField(max_length=128)),
                ('languages', models.CharField(max_length=64)),
                ('specialities', models.CharField(max_length=128)),
                ('sale_properties', models.PositiveSmallIntegerField()),
                ('rent_properties', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('experience', models.PositiveSmallIntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('service_areas', models.ManyToManyField(to='area.area')),
                ('service_cities', models.ManyToManyField(to='area.city')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='area.realestate')),
            ],
            options={
                'verbose_name_plural': 'Agents',
                'db_table': 'agents',
            },
        ),
        migrations.CreateModel(
            name='UnitOfBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed', models.CharField(max_length=32)),
                ('bath', models.CharField(max_length=32)),
                ('area', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('building_link', models.CharField(max_length=128)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('building_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.building')),
                ('complex_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='area.complex')),
                ('detail', models.ManyToManyField(blank=True, null=True, to='area.unitdetail')),
                ('photo', models.ManyToManyField(blank=True, null=True, to='area.unitphoto')),
            ],
            options={
                'verbose_name_plural': 'Unit Of Buildings',
                'db_table': 'unit_of_buildings',
            },
        ),
    ]
