# Generated by Django 5.0.4 on 2024-07-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0002_part_building_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='details',
            field=models.ManyToManyField(blank=True, null=True, to='area.buildingdetail'),
        ),
        migrations.AddField(
            model_name='part',
            name='highlight',
            field=models.ManyToManyField(blank=True, null=True, to='area.buildinghighlight'),
        ),
        migrations.AddField(
            model_name='part',
            name='img_link',
            field=models.ManyToManyField(blank=True, null=True, to='area.buildingimg'),
        ),
        migrations.AddField(
            model_name='part',
            name='is_ok',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='location',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
