# Generated by Django 5.0.4 on 2024-07-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0002_remove_realestate_property_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='area',
        ),
        migrations.RemoveField(
            model_name='building',
            name='city',
        ),
        migrations.RemoveField(
            model_name='building',
            name='community',
        ),
        migrations.RemoveField(
            model_name='building',
            name='details',
        ),
        migrations.RemoveField(
            model_name='building',
            name='highlight',
        ),
        migrations.RemoveField(
            model_name='building',
            name='img_link',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='buildings',
        ),
        migrations.RemoveField(
            model_name='unitofbuilding',
            name='building_name',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='area',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='city',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='community',
        ),
        migrations.RemoveField(
            model_name='unitofbuilding',
            name='complex_name',
        ),
        migrations.RemoveField(
            model_name='unitofbuilding',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='unitofbuilding',
            name='photo',
        ),
        migrations.DeleteModel(
            name='BuildingDetail',
        ),
        migrations.DeleteModel(
            name='BuildingHighlight',
        ),
        migrations.DeleteModel(
            name='BuildingImg',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Complex',
        ),
        migrations.DeleteModel(
            name='UnitDetail',
        ),
        migrations.DeleteModel(
            name='UnitOfBuilding',
        ),
        migrations.DeleteModel(
            name='UnitPhoto',
        ),
    ]
