# Generated by Django 5.0.4 on 2024-07-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0002_complex_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='source',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
