# Generated by Django 5.0.4 on 2024-07-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0003_part_about_part_details_part_highlight_part_img_link_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Part',
            new_name='Buildings',
        ),
        migrations.AlterModelOptions(
            name='buildings',
            options={'verbose_name_plural': 'Buildings'},
        ),
        migrations.DeleteModel(
            name='Building',
        ),
    ]
