# Generated by Django 5.0.4 on 2024-06-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0003_area_source_city_source_community_source_part_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='source',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='city',
            name='source',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='community',
            name='source',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='part',
            name='source',
            field=models.CharField(max_length=128),
        ),
    ]
