# Generated by Django 5.0.4 on 2024-07-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0004_alter_building_publish_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='publish_status',
            field=models.PositiveSmallIntegerField(choices=[('Publish', 1), ('Draft', 0)], default=0),
        ),
    ]
