# Generated by Django 5.0.4 on 2024-07-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0004_rename_part_buildings_alter_buildings_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buildings',
            new_name='Building',
        ),
    ]
