# Generated by Django 5.0.4 on 2024-06-16 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0004_alter_area_source_alter_city_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('link', models.CharField(max_length=128)),
                ('floor', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('area', models.CharField(max_length=64)),
            ],
        ),
    ]
