# Generated by Django 5.0.4 on 2024-07-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0005_rename_buildings_building'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='building',
            table='buildings',
        ),
    ]
