# Generated by Django 5.0.4 on 2024-07-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0005_alter_building_publish_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='publish_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Publish'), (0, 'Draft'), (2, 'Must Be Check')], default=0),
        ),
    ]
