# Generated by Django 5.0.4 on 2024-06-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0005_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='img_link',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
