# Generated by Django 5.0.4 on 2024-07-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0006_alter_building_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
