# Generated by Django 5.0.4 on 2024-07-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0006_alter_building_publish_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='about',
            field=models.TextField(default=None),
        ),
    ]
