# Generated by Django 5.0.4 on 2024-06-16 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0006_building_img_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='floor',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
