# Generated by Django 5.0.4 on 2024-06-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0007_alter_building_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='floor',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
