# Generated by Django 5.0.4 on 2024-07-17 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0007_alter_building_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='source',
        ),
    ]
