# Generated by Django 5.0.4 on 2024-07-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0007_building_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
