# Generated by Django 5.0.4 on 2024-07-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0008_remove_city_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='about',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
