# Generated by Django 5.0.4 on 2024-07-13 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0008_alter_building_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
