# Generated by Django 5.0.4 on 2024-07-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0009_alter_building_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='publish_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Publish'), (0, 'Draft'), (2, 'Must Be Check')], default=0),
        ),
    ]
