# Generated by Django 5.0.4 on 2024-06-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0010_detail_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='floor',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
