# Generated by Django 5.0.4 on 2024-06-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0011_alter_building_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=128)),
                ('img_link', models.CharField(max_length=128)),
            ],
        ),
        migrations.RenameField(
            model_name='building',
            old_name='area',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='building',
            name='category',
        ),
        migrations.RemoveField(
            model_name='building',
            name='city',
        ),
        migrations.RemoveField(
            model_name='building',
            name='floor',
        ),
        migrations.AddField(
            model_name='building',
            name='about',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='building',
            name='img_link',
        ),
        migrations.AddField(
            model_name='building',
            name='img_link',
            field=models.ManyToManyField(to='area.buildingimg'),
        ),
    ]
