# Generated by Django 5.0.4 on 2024-06-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0013_buildingstatus_highlight_building_highlight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='title',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='description',
            new_name='value',
        ),
    ]
