# Generated by Django 5.0.4 on 2024-06-22 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0014_rename_title_detail_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=128)),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UnitPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=128)),
                ('img_link', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='area',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='community',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='part',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='UnitOfBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed', models.CharField(max_length=32)),
                ('bath', models.CharField(max_length=32)),
                ('area', models.CharField(max_length=32)),
                ('desc', models.TextField()),
                ('link', models.CharField(max_length=128)),
                ('building_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.building')),
                ('detail', models.ManyToManyField(to='area.unitdetail')),
                ('photo', models.ManyToManyField(to='area.unitphoto')),
            ],
        ),
    ]
