# Generated by Django 5.0.4 on 2024-06-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0016_rename_building_name_unitofbuilding_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitofbuilding',
            old_name='name',
            new_name='building_name',
        ),
    ]
