# Generated by Django 5.0.4 on 2024-06-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0017_rename_name_unitofbuilding_building_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofbuilding',
            name='detail',
            field=models.ManyToManyField(blank=True, null=True, to='area.unitdetail'),
        ),
    ]
