# Generated by Django 5.0.4 on 2024-06-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0018_alter_unitofbuilding_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofbuilding',
            name='photo',
            field=models.ManyToManyField(blank=True, null=True, to='area.unitphoto'),
        ),
    ]
