# Generated by Django 5.0.4 on 2024-06-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0019_alter_unitofbuilding_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='is_ok',
            field=models.BooleanField(default=False),
        ),
    ]
