# Generated by Django 5.0.4 on 2024-06-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0020_building_is_ok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='is_ok',
            field=models.SmallIntegerField(default=0),
        ),
    ]
