# Generated by Django 5.0.4 on 2024-07-25 08:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Building', '0001_initial'),
        ('RealEstate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_link', models.CharField(max_length=128)),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Unit Details',
                'db_table': 'unit_detials',
            },
        ),
        migrations.CreateModel(
            name='UnitPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_link', models.CharField(max_length=128)),
                ('img_link', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Unit Photos',
                'db_table': 'unit_photos',
            },
        ),
        migrations.CreateModel(
            name='UnitOfBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed', models.CharField(max_length=32)),
                ('bath', models.CharField(max_length=32)),
                ('area', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('building_link', models.CharField(max_length=128)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RealEstate.agent')),
                ('building_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Building.building')),
                ('complex_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Building.complex')),
                ('detail', models.ManyToManyField(blank=True, null=True, to='Unit.unitdetail')),
                ('photo', models.ManyToManyField(blank=True, null=True, to='Unit.unitphoto')),
            ],
            options={
                'verbose_name_plural': 'Unit Of Buildings',
                'db_table': 'unit_of_buildings',
            },
        ),
    ]
