# Generated by Django 5.0.4 on 2024-07-30 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0001_initial'),
        ('Unit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofbuilding',
            name='building_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Building.building'),
        ),
    ]
