# Generated by Django 5.0.4 on 2024-07-30 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0001_initial'),
        ('RealEstate', '0009_delete_propertytype'),
        ('Unit', '0002_alter_unitofbuilding_building_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofbuilding',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='RealEstate.agent'),
        ),
        migrations.AlterField(
            model_name='unitofbuilding',
            name='building_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Building.building'),
        ),
    ]
