# Generated by Django 5.0.4 on 2024-07-30 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0009_delete_propertytype'),
        ('Unit', '0003_alter_unitofbuilding_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofbuilding',
            name='agent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='RealEstate.agent'),
            preserve_default=False,
        ),
    ]
