# Generated by Django 5.0.4 on 2024-07-31 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0009_delete_propertytype'),
        ('Unit', '0005_alter_unitofbuilding_building_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofbuilding',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='RealEstate.realestate'),
        ),
        migrations.AlterField(
            model_name='unitofbuilding',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='RealEstate.agent'),
        ),
    ]
