# Generated by Django 5.0.4 on 2024-07-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unit', '0006_unitofbuilding_agency_alter_unitofbuilding_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofbuilding',
            name='price',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
