# Generated by Django 5.0.4 on 2024-08-03 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Unit', '0007_unitofbuilding_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitofbuilding',
            name='complex_name',
        ),
    ]
