# Generated by Django 5.0.4 on 2024-07-25 08:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0002_remove_realestate_property_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Property Type',
                'db_table': 'property_type',
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('photo', models.CharField(max_length=128)),
                ('sale_properties', models.PositiveSmallIntegerField()),
                ('rent_properties', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('property_types', models.ManyToManyField(to='RealEstate.propertytype')),
                ('service_areas', models.ManyToManyField(to='area.area')),
                ('service_cities', models.ManyToManyField(to='area.city')),
            ],
            options={
                'verbose_name_plural': 'Real Estate',
                'db_table': 'real_estates',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('photo', models.CharField(max_length=128)),
                ('languages', models.CharField(max_length=64)),
                ('specialities', models.CharField(max_length=128)),
                ('sale_properties', models.PositiveSmallIntegerField()),
                ('rent_properties', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('experience', models.PositiveSmallIntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('service_areas', models.ManyToManyField(to='area.area')),
                ('service_cities', models.ManyToManyField(to='area.city')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RealEstate.realestate')),
            ],
            options={
                'verbose_name_plural': 'Agents',
                'db_table': 'agents',
            },
        ),
    ]
