# Generated by Django 5.0.4 on 2024-08-05 11:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('photo', models.CharField(blank=True, max_length=128, null=True)),
                ('link', models.CharField(max_length=128)),
                ('property_types', models.CharField(max_length=256)),
                ('service_areas', models.TextField()),
                ('properties', models.TextField()),
                ('description', models.TextField()),
                ('brn', models.CharField(blank=True, max_length=25, null=True, verbose_name='BRN')),
                ('arra', models.CharField(blank=True, max_length=25, null=True, verbose_name='ARRA')),
                ('ded', models.CharField(blank=True, max_length=25, null=True, verbose_name='DED')),
                ('phone_number', models.CharField(max_length=18)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Real Estate',
                'db_table': 'real_estates',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=128)),
                ('photo', models.CharField(blank=True, max_length=128, null=True)),
                ('languages', models.CharField(max_length=128)),
                ('specialities', models.CharField(max_length=128)),
                ('service_areas', models.TextField()),
                ('properties', models.TextField()),
                ('description', models.TextField()),
                ('experience', models.CharField(blank=True, max_length=128, null=True)),
                ('phone_number', models.CharField(max_length=25)),
                ('brn', models.CharField(blank=True, max_length=25, null=True, verbose_name='BRN')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='RealEstate.agency')),
            ],
            options={
                'verbose_name_plural': 'Agents',
                'db_table': 'agents',
            },
        ),
    ]
