# Generated by Django 5.0.4 on 2024-07-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0003_remove_agent_rent_properties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='brn',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='BRN'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='experience',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
