# Generated by Django 5.0.4 on 2024-07-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0004_alter_agent_brn_alter_agent_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='brn',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='BRN'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='photo',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
