# Generated by Django 5.0.4 on 2024-07-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0005_alter_realestate_brn_alter_realestate_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='phone_number',
            field=models.CharField(default='', max_length=18),
            preserve_default=False,
        ),
    ]
