# Generated by Django 5.0.4 on 2024-07-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0006_realestate_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='arra',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='ARRA'),
        ),
    ]
