# Generated by Django 5.0.4 on 2024-07-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0007_realestate_arra'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='ded',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='DED'),
        ),
    ]
