# Generated by Django 5.0.4 on 2024-07-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0008_realestate_ded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyType',
        ),
    ]
