# Generated by Django 5.0.4 on 2024-07-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0009_delete_propertytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='service_areas',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='service_areas',
            field=models.TextField(),
        ),
    ]
