# Generated by Django 5.0.4 on 2024-08-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0010_alter_agent_service_areas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='arra',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='ARRA'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='brn',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='BRN'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='ded',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='DED'),
        ),
    ]
