# Generated by Django 5.0.4 on 2024-08-03 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0011_alter_realestate_arra_alter_realestate_brn_and_more'),
        ('Unit', '0007_unitofbuilding_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RealEstate',
            new_name='Agency',
        ),
    ]
