# Generated by Django 5.0.4 on 2024-08-03 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0012_rename_realestate_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='real_estate',
        ),
        migrations.AddField(
            model_name='agent',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='RealEstate.agency'),
        ),
    ]
