# Generated by Django 5.0.4 on 2024-08-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0013_remove_agent_real_estate_agent_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='experience',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='languages',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='agent',
            name='properties',
            field=models.CharField(max_length=128),
        ),
    ]
