# Generated by Django 5.0.4 on 2024-08-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0014_alter_agent_experience_alter_agent_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='arra',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='ARRA'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='brn',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='BRN'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='ded',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='DED'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='agency',
            name='properties',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='agency',
            name='property_types',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='agent',
            name='brn',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='BRN'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='agent',
            name='properties',
            field=models.TextField(),
        ),
    ]
