# Generated by Django 5.0.4 on 2024-07-25 08:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0003_remove_building_area_remove_building_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_link', models.CharField(max_length=128)),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Building Detials',
                'db_table': 'building_details',
            },
        ),
        migrations.CreateModel(
            name='BuildingHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_link', models.CharField(max_length=128)),
                ('highlight', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Building Highlights',
                'db_table': 'building_highlights',
            },
        ),
        migrations.CreateModel(
            name='BuildingImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_link', models.CharField(max_length=128)),
                ('img_link', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Building Images',
                'db_table': 'building_images',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=128)),
                ('building_link', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('location', models.CharField(blank=True, max_length=64, null=True)),
                ('about', models.TextField(blank=True, default=None, null=True)),
                ('publish_status', models.PositiveSmallIntegerField(choices=[(1, 'Publish'), (0, 'Draft'), (2, 'Must Be Check')], default=0)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='area.area')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='area.city')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='area.community')),
                ('details', models.ManyToManyField(blank=True, null=True, to='Building.buildingdetail')),
                ('highlight', models.ManyToManyField(blank=True, null=True, to='Building.buildinghighlight')),
                ('img_link', models.ManyToManyField(blank=True, null=True, to='Building.buildingimg')),
            ],
            options={
                'verbose_name_plural': 'Buildings',
                'db_table': 'buildings',
            },
        ),
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('publish_status', models.PositiveSmallIntegerField(choices=[(1, 'Publish'), (0, 'Draft'), (2, 'Must Be Check')], default=0)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='area.area')),
                ('buildings', models.ManyToManyField(to='Building.building')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='area.city')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='area.community')),
            ],
            options={
                'verbose_name_plural': 'Complexs',
                'db_table': 'complexs',
            },
        ),
    ]
