# Generated by Django 5.0.4 on 2024-08-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0002_alter_buildingimg_building_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildinghighlight',
            name='highlight',
            field=models.CharField(max_length=128),
        ),
    ]
