# Generated by Django 5.0.4 on 2024-08-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0003_alter_buildingdetail_building_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildinghighlight',
            name='highlight',
            field=models.CharField(max_length=320),
        ),
    ]
