# Generated by Django 5.0.4 on 2024-08-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0004_alter_buildinghighlight_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildinghighlight',
            name='highlight',
            field=models.CharField(max_length=500),
        ),
    ]
