# Generated by Django 5.0.4 on 2024-08-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0005_alter_buildinghighlight_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdetail',
            name='key',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='buildinghighlight',
            name='highlight',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='buildingimg',
            name='img_link',
            field=models.TextField(),
        ),
    ]
