# Generated by Django 5.0.4 on 2024-08-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0006_alter_buildingdetail_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdetail',
            name='key',
            field=models.CharField(max_length=320),
        ),
        migrations.AlterField(
            model_name='buildingdetail',
            name='value',
            field=models.CharField(max_length=320),
        ),
    ]
